using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;

namespace MyNewProject.ViewModels;

/// <summary>
/// Child view model that owns the collection of items.
///
/// Lesson 6 changed four things here:
/// 1. properties are generated by [ObservableProperty], commands by [RelayCommand]
///    (that is why the class is now 'partial');
/// 2. LoadCommand is an IAsyncRelayCommand: it knows itself whether it is running
///    (IsRunning) and refuses to start twice - the manual IsLoading flag is gone;
/// 3. LoadAsync takes a CancellationToken, so IncludeCancelCommand gives us a
///    ready-made LoadCancelCommand for free;
/// 4. a failure is a normal state of the view model (ErrorMessage), not a crash -
///    which is exactly what 'async void' could not give us.
///
/// The two notification mechanisms from lesson 3 are still here:
/// ObservableCollection.CollectionChanged (items added/removed) and
/// PropertyChanged of every item (IsDone), both feeding the counters.
/// </summary>
internal partial class TodoListViewModel : ObservableObject
{
    [ObservableProperty]
    [NotifyCanExecuteChangedFor(nameof(AddCommand))]
    private string _newTitle = string.Empty;

    [ObservableProperty]
    private TodoItemViewModel? _selectedItem;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(HasError))]
    private string? _errorMessage;

    /// <summary>Lesson switch: makes the fake server throw, so we can watch the catch block.</summary>
    [ObservableProperty]
    private bool _simulateError;

    public TodoListViewModel()
    {
        Items.CollectionChanged += OnItemsCollectionChanged;
    }

    public ObservableCollection<TodoItemViewModel> Items { get; } = new();

    public bool HasError => !string.IsNullOrEmpty(ErrorMessage);

    public int TotalCount => Items.Count;
    public int DoneCount => Items.Count(item => item.IsDone);
    public int ActiveCount => TotalCount - DoneCount;

    public void Clear()
    {
        Items.Clear();
        NewTitle = string.Empty;
        SelectedItem = null;
        ErrorMessage = null;
    }

    /// <summary>
    /// The generator turns this into LoadCommand (IAsyncRelayCommand) plus
    /// LoadCancelCommand (ICommand), which is enabled only while the task runs.
    /// </summary>
    [RelayCommand(IncludeCancelCommand = true)]
    private async Task LoadAsync(CancellationToken token)
    {
        ErrorMessage = null;

        // Without this a second Load would simply append a copy of everything.
        Items.Clear();

        try
        {
            // Pretend we are calling a server. Passing the token is what makes
            // the wait interruptible - Task.Delay(5000) alone ignores Cancel.
            await Task.Delay(5000, token);

            if (SimulateError)
                throw new InvalidOperationException("The server is down. Try again later.");

            Items.Add(new TodoItemViewModel("Learn properties and bindings") { IsDone = true });
            Items.Add(new TodoItemViewModel("Learn nested view models"));
            Items.Add(new TodoItemViewModel("Learn collections"));
        }
        catch (OperationCanceledException)
        {
            // Cancellation is not a failure - the user asked for it. Always a separate branch.
            ErrorMessage = "Loading cancelled.";
        }
        catch (Exception ex)
        {
            // Inside 'async void' this exception would have killed the application.
            // Inside 'async Task' behind an async command it is just a value we can show.
            ErrorMessage = ex.Message;
        }
    }

    [RelayCommand(CanExecute = nameof(CanAdd))]
    private void Add()
    {
        Items.Add(new TodoItemViewModel(NewTitle.Trim()));
        NewTitle = string.Empty;
    }

    private bool CanAdd() => !string.IsNullOrWhiteSpace(NewTitle);

    [RelayCommand(CanExecute = nameof(CanRemove))]
    private void Remove(TodoItemViewModel? item)
    {
        if (item != null)
            Items.Remove(item);
    }

    // A CanExecute of a parametrised command takes the same parameter.
    private bool CanRemove(TodoItemViewModel? item) => item is not null;

    [RelayCommand(CanExecute = nameof(CanClearDone))]
    private void ClearDone()
    {
        foreach (var done in Items.Where(item => item.IsDone).ToList())
            Items.Remove(done);
    }

    private bool CanClearDone() => DoneCount > 0;

    private void OnItemsCollectionChanged(object? sender, NotifyCollectionChangedEventArgs e)
    {
        // The parent listens to its children, and stops listening when they leave the list.
        foreach (var item in e.OldItems?.OfType<TodoItemViewModel>() ?? [])
            item.PropertyChanged -= OnItemPropertyChanged;

        foreach (var item in e.NewItems?.OfType<TodoItemViewModel>() ?? [])
            item.PropertyChanged += OnItemPropertyChanged;

        RaiseCountersChanged();
    }

    private void OnItemPropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (e.PropertyName == nameof(TodoItemViewModel.IsDone))
            RaiseCountersChanged();
    }

    private void RaiseCountersChanged()
    {
        OnPropertyChanged(nameof(TotalCount));
        OnPropertyChanged(nameof(DoneCount));
        OnPropertyChanged(nameof(ActiveCount));

        // Computed counters cannot be tracked by [NotifyCanExecuteChangedFor],
        // so this one stays manual.
        ClearDoneCommand.NotifyCanExecuteChanged();
    }
}
